export const GAME_CONFIG = {
  slug: "museum-statues",
  title: "박물관 조각상 (Museum Statues)",
  summary: "경비원의 손전등이 지나갈 때는 조각상처럼 멈추고, 불빛이 사라지면 춤춰요.",
  creator: "Manse",
  sourceUrl: "https://github.com/ahndohun/manse-game-museum-statues",
  locale: "ko",
  heroPath: "/packs/museum-statues/assets/images/night-museum-hero.png",
} as const;

export type SupportedLocale = "ko" | "en";

export const UI_COPY = {
  ko: {
    languageLabel: "언어 선택",
    kicker: "독립형 Manse 움직임 게임",
    title: "박물관 조각상",
    summary: "손전등이 비추면 조각상처럼 꼼짝 말고, 불빛이 사라지면 신나게 춤춰요.",
    heroAlt: "달빛이 비치는 밤의 박물관에서 대리석 조각상들이 춤추고 경비원의 손전등이 바닥을 비추는 모습",
    galleryLabel: "야간 전시실 · 멈춤 / 춤",
    privacy: "카메라는 이 기기에서만 처리돼요 · 계정 불필요 · 분석 도구 없음",
    playerLabel: "박물관 조각상 게임 플레이어",
    stageLabel: "움직임 게임 무대",
    startGuide: "포인터 모드로 먼저 연습해 보세요. 카메라는 선택 사항이며, 카메라 버튼을 눌렀을 때만 권한을 요청해요.",
    playPointer: "포인터로 플레이",
    useCamera: "내 카메라 사용",
    restartPointer: "포인터로 다시 시작",
    switchCamera: "카메라로 전환",
    comfortableSpace: "안전하고 편안하게 움직일 수 있는 공간을 골라 주세요.",
    statusAttention: "확인이 필요해요",
    statusStarting: "준비 중",
    statusComplete: "완료",
    statusIdle: "플레이 방식을 골라 주세요",
    statusCamera: "카메라 영상은 기기 안에서만 처리돼요",
    statusSimulator: "포인터 모드 실행 중",
    runtimeReady: "런타임 준비됨",
    tier: "단계",
    errorGeneric: "게임을 시작하지 못했어요. 다시 시도하거나 포인터 모드를 선택해 주세요.",
    footer: "Manse 제작. 오픈소스 Manse 엔진으로 만들었습니다. 움직임이 불편하면 언제든 멈추세요.",
    source: "소스 코드 보기",
  },
  en: {
    languageLabel: "Choose language",
    kicker: "Independent Manse motion game",
    title: "Museum Statues",
    summary: "Hold perfectly still when the flashlight finds you, then dance when the beam slips away.",
    heroAlt: "Marble statues dancing in a moonlit museum as a guard's flashlight sweeps across the floor",
    galleryLabel: "Night gallery · freeze / dance",
    privacy: "Camera stays on this device · no account · no analytics",
    playerLabel: "Museum Statues game player",
    stageLabel: "Interactive motion game stage",
    startGuide: "Try the pointer first. Camera play is optional and asks permission only after you choose it.",
    playPointer: "Play with pointer",
    useCamera: "Use my camera",
    restartPointer: "Restart with pointer",
    switchCamera: "Switch to camera",
    comfortableSpace: "Choose a private, comfortable space where you can move safely.",
    statusAttention: "Needs attention",
    statusStarting: "Starting",
    statusComplete: "Complete",
    statusIdle: "Choose how to play",
    statusCamera: "Camera stays on this device",
    statusSimulator: "Pointer mode live",
    runtimeReady: "runtime ready",
    tier: "tier",
    errorGeneric: "The game could not start. Try again or choose pointer mode.",
    footer: "Created by Manse with the open-source Manse engine. Stop whenever movement feels uncomfortable.",
    source: "View source",
  },
} as const;
