export const GAME_CONFIG = {
  slug: "museum-statues",
  title: "박물관 조각상 (Museum Statues)",
  summary: "경비원의 손전등이 지나갈 때는 조각상처럼 멈추고, 불빛이 사라지면 춤춰요.",
  creator: "Manse",
  sourceUrl: "https://github.com/ahndohun/manse-game-museum-statues",
  locale: "ko",
  heroPath: "/packs/museum-statues/assets/images/night-museum-hero.png",
} as const;

/** Designer-owned presentation tuning for the code-native museum renderer. */
export const MUSEUM_FEEL = {
  totalRounds: 5,
  beamSweepMs: 3_800,
  reactionFlashMs: 720,
  roundCelebrationMs: 900,
  palette: {
    night: "#070b22",
    indigo: "#111943",
    marble: "#f0e7d5",
    marbleShade: "#a9abc2",
    gold: "#efc86d",
    amber: "#ffdf91",
    alert: "#ff8e79",
    success: "#8be3c1",
  },
} as const;

export type SupportedLocale = "ko" | "en";

export const UI_COPY = {
  ko: {
    languageLabel: "언어 선택",
    kicker: "독립형 Manse 움직임 게임",
    title: "박물관 조각상",
    summary: "손전등이 비추면 조각상처럼 꼼짝 말고, 불빛이 사라지면 신나게 춤춰요.",
    heroAlt: "달빛이 비치는 밤의 박물관에서 대리석 조각상들이 춤추고 경비원의 손전등이 바닥을 비추는 모습",
    galleryLabel: "야간 전시실 · 멈춤 / 춤",
    privacy: "카메라는 이 기기에서만 처리돼요 · 계정 불필요 · 분석 도구 없음",
    playerLabel: "박물관 조각상 게임 플레이어",
    stageLabel: "움직임 게임 무대",
    startGuide: "포인터 모드로 먼저 연습해 보세요. 카메라는 선택 사항이며, 카메라 버튼을 눌렀을 때만 권한을 요청해요.",
    playPointer: "포인터로 플레이",
    useCamera: "내 카메라 사용",
    restartPointer: "포인터로 다시 시작",
    switchCamera: "카메라로 전환",
    comfortableSpace: "안전하고 편안하게 움직일 수 있는 공간을 골라 주세요.",
    statusAttention: "확인이 필요해요",
    statusStarting: "준비 중",
    statusComplete: "완료",
    statusIdle: "플레이 방식을 골라 주세요",
    statusCamera: "카메라 영상은 기기 안에서만 처리돼요",
    statusSimulator: "포인터 모드 실행 중",
    errorGeneric: "게임을 시작하지 못했어요. 다시 시도하거나 포인터 모드를 선택해 주세요.",
    renderer: {
      wing: "달빛 전시관 04",
      mission: "경비원의 눈을 피해 살아 움직이는 조각상이 되세요",
      freeze: "꼼짝 마!",
      freezeHint: "손전등이 비춰요 · 조각상 자세를 유지하세요",
      holding: "완벽한 조각상",
      holdingHint: "그대로 유지하면 전시 별을 얻어요",
      dance: "지금 춤춰요!",
      danceHint: "불빛이 사라졌어요 · 다음 순찰 전까지 움직여요",
      reset: "앗, 움직였어요!",
      resetHint: "괜찮아요 · 다시 조각상처럼 멈춰 보세요",
      roundClear: "전시 별을 찾았어요!",
      roundClearHint: "멋진 자세예요 · 다음 순찰이 오기 전에 춤춰요",
      framing: "전신이 보이도록 한 걸음 조절해 주세요",
      galleryStars: "전시 별",
      guard: "경비 순찰",
      complete: "박물관의 걸작!",
      completeHint: "밤의 전시관이 당신의 멋진 조각상 자세에 박수를 보내요",
    },
    footer: "Manse 제작. 오픈소스 Manse 엔진으로 만들었습니다. 움직임이 불편하면 언제든 멈추세요.",
    source: "소스 코드 보기",
  },
  en: {
    languageLabel: "Choose language",
    kicker: "Independent Manse motion game",
    title: "Museum Statues",
    summary: "Hold perfectly still when the flashlight finds you, then dance when the beam slips away.",
    heroAlt: "Marble statues dancing in a moonlit museum as a guard's flashlight sweeps across the floor",
    galleryLabel: "Night gallery · freeze / dance",
    privacy: "Camera stays on this device · no account · no analytics",
    playerLabel: "Museum Statues game player",
    stageLabel: "Interactive motion game stage",
    startGuide: "Try the pointer first. Camera play is optional and asks permission only after you choose it.",
    playPointer: "Play with pointer",
    useCamera: "Use my camera",
    restartPointer: "Restart with pointer",
    switchCamera: "Switch to camera",
    comfortableSpace: "Choose a private, comfortable space where you can move safely.",
    statusAttention: "Needs attention",
    statusStarting: "Starting",
    statusComplete: "Complete",
    statusIdle: "Choose how to play",
    statusCamera: "Camera stays on this device",
    statusSimulator: "Pointer mode live",
    errorGeneric: "The game could not start. Try again or choose pointer mode.",
    renderer: {
      wing: "MOONLIGHT WING 04",
      mission: "Come alive without letting the night guard catch you",
      freeze: "FREEZE!",
      freezeHint: "The flashlight found you · hold your statue pose",
      holding: "MASTERFUL STATUE",
      holdingHint: "Stay still to earn a gallery star",
      dance: "DANCE NOW!",
      danceHint: "The beam is gone · move before the next patrol",
      reset: "ALMOST CAUGHT!",
      resetHint: "That is okay · settle back into your statue pose",
      roundClear: "GALLERY STAR EARNED!",
      roundClearHint: "Brilliant pose · dance before the next patrol arrives",
      framing: "Adjust one step so your whole body is visible",
      galleryStars: "GALLERY STARS",
      guard: "GUARD PATROL",
      complete: "MUSEUM MASTERPIECE!",
      completeHint: "The whole night gallery applauds your brilliant statue poses",
    },
    footer: "Created by Manse with the open-source Manse engine. Stop whenever movement feels uncomfortable.",
    source: "View source",
  },
} as const;
